In [27]:
import pandas as pd
import numpy as np

In [34]:
df = pd.read_csv("D:/Estiven/Datos/Proyectos/statistics-of-use-project/data/processed/app_usage_time_motorola.csv", 
                 delimiter=";",
                 index_col='date',
                 parse_dates=['date'])
df.head(2)

,Amazon Shopping,Android System,Biblioapp UdeA,Bing,Calculator,Calculator_1,Calendar,Call Management,Camera,Camera_2,...,Twitch,Twitter,tyba,Upwork Talent,VpnDialogs,Wallpapers,WhatsApp,YouTube,YouTube Music,Zoom
date,,,,,,,,,,,,,,,,,,,,,
2022-10-19,0s,4s,0s,0s,3m 1s,0s,1m 30s,0s,0s,15s,...,0s,0s,0s,0s,0s,0s,1h 13m 6s,0s,0s,0s
2022-10-20,0s,4s,0s,0s,1m 34s,0s,0s,0s,0s,8m 14s,...,0s,0s,0s,0s,0s,0s,1h 1m 50s,12m 59s,0s,0s

In [33]:
# Iterate over each column in the DataFrame
for col in df.columns:
    # Convert the column values to duration format
    df[col] = round(pd.to_timedelta(df[col]).dt.total_seconds() / 60, 2)

# Convert the DataFrame to duration data type
df

,Amazon Shopping,Android System,Biblioapp UdeA,Bing,Calculator,Calculator_1,Calendar,Call Management,Camera,Camera_2,...,Twitch,Twitter,tyba,Upwork Talent,VpnDialogs,Wallpapers,WhatsApp,YouTube,YouTube Music,Zoom
date,,,,,,,,,,,,,,,,,,,,,
2022-10-19,0.00,0.07,0.0,0.0,3.02,0.0,1.50,0.0,0.0,0.25,...,0.0,0.00,0.00,0.00,0.0,0.0,73.10,0.00,0.00,0.0
2022-10-20,0.00,0.07,0.0,0.0,1.57,0.0,0.00,0.0,0.0,8.23,...,0.0,0.00,0.00,0.00,0.0,0.0,61.83,12.98,0.00,0.0
2022-10-21,0.00,0.00,0.0,0.0,0.00,0.0,0.00,0.0,0.0,1.02,...,0.0,0.00,0.00,0.00,0.0,0.0,62.60,0.00,0.00,0.0
2022-10-22,0.00,0.15,0.0,0.0,0.00,0.0,0.00,0.0,0.0,9.73,...,0.0,0.00,0.00,0.00,0.0,0.0,113.32,33.82,0.00,0.0
2022-10-24,0.00,0.20,0.0,0.0,6.67,0.0,0.00,0.0,0.0,7.88,...,0.0,0.00,0.00,0.00,0.0,0.0,90.28,3.92,0.00,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2023-05-24,0.12,0.17,0.0,0.0,14.73,0.0,0.02,0.0,0.0,6.35,...,0.0,1.47,0.00,0.00,0.0,0.0,40.22,59.38,0.00,0.0
2023-05-28,0.00,0.02,0.0,0.0,0.37,0.0,0.00,0.0,0.0,0.13,...,0.0,0.00,0.00,0.00,0.0,0.0,33.25,86.02,0.00,0.0
2023-05-29,0.00,0.10,0.0,0.0,0.00,0.0,0.00,0.0,0.0,2.42,...,0.0,0.47,0.00,0.00,0.0,0.0,42.12,0.00,0.00,0.0
2023-05-30,1.63,0.07,0.0,0.0,0.57,0.0,0.03,0.0,0.0,0.55,...,0.0,0.00,45.28,6.77,0.0,0.0,100.42,62.63,0.00,0.0
2023-06-05,0.00,0.18,0.0,0.0,2.15,0.0,0.00,0.0,0.0,0.00,...,0.0,0.00,0.00,4.58,0.0,0.0,88.18,11.08,8.62,0.0

In [35]:
pd.to_timedelta('1h 15m')

Timedelta('0 days 01:15:00')